"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from dotenv import load_dotenv
load_dotenv()
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = []
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
INSTALLED_APPS = [
    "jazzmin",
    'allauth',
    'allauth.account',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize', 
    'widget_tweaks',
    'home',
    'app1',
]
SITE_ID = 1
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]
ROOT_URLCONF = 'mysite.urls'

GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Thay đổi dòng dưới đây:
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Thêm dòng này để xem lỗi tốt hơn
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True
USE_L10N = True
USE_TZ = True


SILENCED_SYSTEM_CHECKS = ["models.W036", "models.W043"]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


# ... các cài đặt khác ...

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = 'home'

# Cho phép đăng ký tài khoản mới
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'

# === CÀI ĐẶT MỚI CHO ALLAUTH (phiên bản mới) ===
ACCOUNT_LOGIN_METHODS = {'username', 'email'}  # Cho phép đăng nhập bằng cả username và email
ACCOUNT_SIGNUP_FIELDS = ['email', 'username*', 'password1*', 'password2*']  # email tùy chọn, username và password bắt buộc
ACCOUNT_LOGOUT_ON_GET = True
# === CÁC CÀI ĐẶT CŨ (COMMENT HOẶC XÓA) ===
# ACCOUNT_AUTHENTICATION_METHOD = 'username_email' # Đã được thay thế bởi ACCOUNT_LOGIN_METHODS
# ACCOUNT_EMAIL_REQUIRED = False                  # Đã được thay thế bởi ACCOUNT_SIGNUP_FIELDS
# ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True      # Đã được thay thế bởi ACCOUNT_SIGNUP_FIELDS

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]
JAZZMIN_SETTINGS = {
    "site_title": "WatchStore Admin",
    "site_header": "Quản lý WatchStore",
    "site_brand": "WatchStore",

    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,

    # Icon từng model
    "icons": {
        # App1
        "app1.Brand": "fas fa-tag",
        "app1.Watch": "fas fa-clock",
        "app1.Order": "fas fa-shopping-cart",
        "app1.Profile": "fas fa-user",
        "app1.Notification": "fas fa-bell",
        "app1.Cart": "fas fa-cart-plus",
        "app1.Refund": "fas fa-undo-alt",

        # Django mặc định
        "auth.User": "fas fa-users",
        "auth.Group": "fas fa-user-shield",
        "sites.Site": "fas fa-globe",
    },

    # Custom link Doanh thu
    "custom_links": {
        "app1": [{
            "name": "Doanh thu",
            "url": "admin:doanh_thu",
            "icon": "fas fa-chart-line",
        }]
    }

}