# Generated by Django 6.0.1 on 2026-01-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='brand',
            field=models.TextField(blank=True),
        ),
    ]
