# Generated by Django 6.0.2 on 2026-02-21 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app1.brand'),
        ),
    ]
