# Generated by Django 6.0.1 on 2026-02-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
