# Generated by Django 6.0.1 on 2026-02-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_watch_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
