# Generated by Django 6.0.1 on 2026-02-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_watch_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
