# Generated by Django 6.0.1 on 2026-02-22 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_watch_is_sold_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='case_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chất liệu vỏ'),
        ),
        migrations.AddField(
            model_name='watch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='diameter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Đường kính mặt'),
        ),
        migrations.AddField(
            model_name='watch',
            name='gender',
            field=models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Unisex', 'Unisex')], max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='watch',
            name='glass_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chất liệu kính'),
        ),
        migrations.AddField(
            model_name='watch',
            name='movement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bộ máy'),
        ),
        migrations.AddField(
            model_name='watch',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='sold_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watch',
            name='strap_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chất liệu dây'),
        ),
        migrations.AddField(
            model_name='watch',
            name='thickness',
            field=models.CharField(blank=True, max_length=50, verbose_name='Độ dày'),
        ),
        migrations.AddField(
            model_name='watch',
            name='warranty',
            field=models.CharField(blank=True, default='24 tháng', max_length=100, verbose_name='Bảo hành'),
        ),
        migrations.AddField(
            model_name='watch',
            name='water_resistance',
            field=models.CharField(blank=True, max_length=50, verbose_name='Chống nước'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app1.cart')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.watch')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app1_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
