# Generated by Django 6.0.2 on 2026-02-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_watch_case_material_watch_created_at_watch_diameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='case_material',
        ),
        migrations.AddField(
            model_name='watch',
            name='case_color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Màu vỏ'),
        ),
        migrations.AddField(
            model_name='watch',
            name='case_diameter',
            field=models.CharField(blank=True, max_length=100, verbose_name='Đường kính mặt'),
        ),
        migrations.AddField(
            model_name='watch',
            name='design_style',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kiểu thiết kế'),
        ),
        migrations.AddField(
            model_name='watch',
            name='dial_color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Màu mặt'),
        ),
        migrations.AddField(
            model_name='watch',
            name='dial_shape',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hình dáng mặt'),
        ),
        migrations.AddField(
            model_name='watch',
            name='features',
            field=models.TextField(blank=True, verbose_name='Tiện ích'),
        ),
        migrations.AddField(
            model_name='watch',
            name='power_reserve',
            field=models.CharField(blank=True, max_length=100, verbose_name='Khoảng trữ cót'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='diameter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Size mặt'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='gender',
            field=models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Unisex', 'Unisex')], max_length=10, verbose_name='Đối tượng'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='movement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Loại máy'),
        ),
    ]
