# Generated by Django 6.0.2 on 2026-02-22 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_watch_case_material_watch_case_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='case_color',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='case_diameter',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='design_style',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='dial_color',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='dial_shape',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='features',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='power_reserve',
        ),
        migrations.AddField(
            model_name='watch',
            name='case_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chất liệu vỏ'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='diameter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Đường kính mặt'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='gender',
            field=models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Unisex', 'Unisex')], max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='movement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bộ máy'),
        ),
        migrations.CreateModel(
            name='WatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('order', models.IntegerField(default=0)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='app1.watch')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
