# Generated by Django 6.0.2 on 2026-02-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_watchimage_options_remove_watch_case_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='power_reserve',
        ),
        migrations.AddField(
            model_name='watch',
            name='series',
            field=models.CharField(blank=True, max_length=100, verbose_name='Series'),
        ),
    ]
