# Generated by Django 6.0.2 on 2026-03-05 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchimage',
            options={},
        ),
        migrations.CreateModel(
            name='WatchDescImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='watch_desc/')),
                ('caption', models.TextField(blank=True, help_text='Đoạn chữ hiển thị bên cạnh ảnh (chỉ dùng khi chọn layout trái/phải)')),
                ('layout', models.CharField(choices=[('full', '📷 Ảnh toàn chiều rộng'), ('float_left', '◧ Ảnh trái — chữ bên phải'), ('float_right', '◨ Ảnh phải — chữ bên trái')], default='full', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị (số nhỏ hiện trước)')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desc_images', to='app1.watch')),
            ],
            options={
                'verbose_name': 'Ảnh sản phẩm',
                'verbose_name_plural': 'Ảnh sản phẩm',
                'ordering': ['order'],
            },
        ),
    ]
