# Generated by Django 6.0.2 on 2026-03-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_watchimage_options_watchdescimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchdescimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Không bắt buộc — để trống nếu chỉ cần thêm chữ', null=True, upload_to='watch_desc/'),
        ),
        migrations.AlterField(
            model_name='watchdescimage',
            name='layout',
            field=models.CharField(choices=[('full', '📷 Ảnh toàn chiều rộng'), ('float_left', '◧ Ảnh trái — chữ bên phải'), ('float_right', '◨ Ảnh phải — chữ bên trái')], default='full', help_text='Kiểu hiển thị', max_length=20),
        ),
    ]
