# Generated by Django 6.0.2 on 2026-03-08 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_watchdescimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(help_text='Ảnh poster bên trái', upload_to='showcase/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị (số nhỏ lên trước)')),
                ('is_active', models.BooleanField(default=True, help_text='Bật/tắt hiển thị')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='showcase', to='app1.brand')),
            ],
            options={
                'verbose_name': 'Hãng nổi bật',
                'verbose_name_plural': 'Hãng nổi bật trang chủ',
                'ordering': ['order'],
            },
        ),
    ]
