# Generated by Django 6.0.2 on 2026-03-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_review_image2_review_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('waiting_confirm', 'Chờ xác nhận'), ('paid', 'Đã thanh toán')], default='pending', max_length=20),
        ),
    ]
