# Generated by Django 6.0.2 on 2026-03-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='category',
            field=models.CharField(choices=[('watch', 'Đồng Hồ'), ('strap', 'Dây Đồng Hồ'), ('box', 'Hộp Đựng Đồng Hồ')], default='watch', max_length=20, verbose_name='Danh mục'),
        ),
    ]
