# Generated by Django 6.0.2 on 2026-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_watch_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Phụ kiện',
                'verbose_name_plural': 'Phụ kiện (Dây & Hộp)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app1.watch',),
        ),
        migrations.AlterModelOptions(
            name='watchdescimage',
            options={'ordering': ['order'], 'verbose_name': 'Ảnh mô tả chi tiết', 'verbose_name_plural': 'Ảnh mô tả sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='watchimage',
            options={'ordering': ['order'], 'verbose_name': 'Ảnh sản phẩm', 'verbose_name_plural': 'Ảnh sản phẩm'},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên sự kiện')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Ảnh banner')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Giảm giá (%)')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('upcoming', '🕐 Sắp diễn ra'), ('active', '✅ Đang diễn ra'), ('ended', '⛔ Đã kết thúc')], default='upcoming', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị trên web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('watches', models.ManyToManyField(blank=True, related_name='events', to='app1.watch', verbose_name='Sản phẩm áp dụng')),
            ],
            options={
                'verbose_name': 'Sự kiện',
                'verbose_name_plural': 'Sự kiện & Khuyến mãi',
                'ordering': ['-start_date'],
            },
        ),
    ]
