# Generated by Django 6.0.2 on 2026-04-22 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_order_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('waiting_confirm', 'Chờ xác nhận'), ('paid', 'Đã thanh toán'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Tên ngân hàng')),
                ('bank_account', models.CharField(max_length=50, verbose_name='Số tài khoản')),
                ('account_holder', models.CharField(max_length=150, verbose_name='Chủ tài khoản')),
                ('reason', models.TextField(verbose_name='Lý do hoàn tiền')),
                ('status', models.CharField(choices=[('pending', '⏳ Chờ xử lý'), ('completed', '✅ Đã hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn tiền')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='app1.order', verbose_name='Đơn hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Yêu cầu hoàn tiền',
                'verbose_name_plural': 'Yêu cầu hoàn tiền',
                'ordering': ['-created_at'],
            },
        ),
    ]
