# Generated by Django 6.0.2 on 2026-04-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_order_payment_status_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã hoàn tiền'), ('rejected', 'Từ chối hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
